# -*-mode: toml;-*- vim:ft=toml
# file: chezmoi/.chezmoiexternal.toml

[".asdf"]
    url = "https://github.com/asdf-vm/asdf.git"
    type = "git-repo"
    refreshPeriod = "168h"
    [".asdf".clone]
        args = ["--branch", "{{ .asdf_version }}", "--depth", "1"]
    [".asdf".pull]
        args = ["--ff-only"]

[".local/bin/tsh"]
    type = "file"
    url = "https://cdn.teleport.dev/teleport-{{ .teleport_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}-bin.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/tsh".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "teleport/tsh"]

[".local/bin/tctl"]
    type = "file"
    url = "https://cdn.teleport.dev/teleport-{{ .teleport_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}-bin.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/tctl".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "teleport/tctl"]

[".local/bin/starship"]
    type = "file"
    url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-{{ .chezmoi.os }}-gnu.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/starship".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "starship"]

[".local/bin/helm"]
    type = "file"
    url = "https://get.helm.sh/helm-{{ .helm_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/helm".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "{{ .chezmoi.os }}-{{ .chezmoi.arch }}/helm"]

[".local/bin/shellcheck"]
    type = "file"
    url = "https://github.com/koalaman/shellcheck/releases/download/{{ .shellcheck_version }}/shellcheck-{{ .shellcheck_version }}.{{ .chezmoi.os }}.{{ eq .chezmoi.arch "amd64" | ternary "x86_64" .chezmoi.arch }}.tar.xz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/shellcheck".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "-J", "--to-stdout", "shellcheck-{{ .shellcheck_version }}/shellcheck"]

[".local/bin/shfmt"]
    type = "file"
    url = "https://github.com/mvdan/sh/releases/download/{{ .shfmt_version }}/shfmt_{{ .shfmt_version }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/shfmt".checksum]
        sha256 = "5741a02a641de7e56b8da170e71a97e58050d66a3cf485fb268d6a5a8bb74afb"

[".local/bin/influx"]
    type = "file"
    url = "https://dl.influxdata.com/influxdb/releases/influxdb2-client-{{ .influx_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/influx".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "influxdb2-client-{{ .influx_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}/influx"]

[".local/bin/getignore"]
    type = "file"
    url = "https://github.com/gotgenes/getignore/releases/download/v{{ .getignore_version }}/getignore-{{ .getignore_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/getignore".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "getignore-{{ .getignore_version }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}/getignore"]

[".local/bin/fossa"]
    type = "file"
    url = "https://github.com/fossas/fossa-cli/releases/download/v3.6.10/fossa_3.6.10_linux_amd64.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/fossa".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fossa"]
    [".local/bin/fossa".checksum]
        sha256 = "2b6a0d739af709c3fa73232e909288ee8dd4d30cd0f9c9c4e65082bc1c7b8d45"
